{
 "title": "Business",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location",
    "query": "select name from appointments_location"
   }
  ]
 },
 "panels": [
  { "title": "Sample Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Samples taken TODAY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom samples_sample as sample\ninner join appointments_seat as seat on sample.seat_id = seat.uuid\ninner join appointments_appointment as appt on seat.appointment_id = appt.uuid\nwhere \n  DATE(sampled_at) = DATE(NOW())\n  AND appt.location_id in (select id from appointments_location where name = '$location')"
    }
   ]
  },
  {
   "title": "Seats taken TODAY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "select \n  sum(apt.seats) as seats_taken\nfrom appointments_timeslot as slot\ninner join (\n  select\n    appointments_appointment.uuid,\n    time_slot_id,\n    count(seat.uuid) as seats\n  from appointments_appointment\n  inner join appointments_seat as seat\n    on appointments_appointment.uuid = seat.appointment_id\n  where is_registration_completed = 'true'\n  group by appointments_appointment.uuid\n) as apt\n  on  slot.uuid = apt.time_slot_id\nwhere DATE(slot.start) = CURRENT_DATE\nand location_id in (select id from appointments_location where name = '$location')\ngroup by\n  slot.start,\n  slot.capacity,\n  slot.usage\n"
    }
   ]
  },
  {
   "title": "Seats taken Tomorrow",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "select \n  sum(apt.seats) as seats_taken\nfrom appointments_timeslot as slot\ninner join (\n  select\n    appointments_appointment.uuid,\n    time_slot_id,\n    count(seat.uuid) as seats\n  from appointments_appointment\n  inner join appointments_seat as seat\n    on appointments_appointment.uuid = seat.appointment_id\n  where is_registration_completed = 'true'\n  group by appointments_appointment.uuid\n) as apt\n  on  slot.uuid = apt.time_slot_id\nwhere DATE(slot.start) = CURRENT_DATE + interval '1 day'\nand location_id in (select id from appointments_location where name = '$location')\ngroup by\n  slot.start,\n  slot.capacity,\n  slot.usage\n"
    }
   ]
  },
  {
   "title": "Seats taken D After Tomorrow",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select \n  sum(apt.seats) as seats_taken\nfrom appointments_timeslot as slot\ninner join (\n  select\n    appointments_appointment.uuid,\n    time_slot_id,\n    count(seat.uuid) as seats\n  from appointments_appointment\n  inner join appointments_seat as seat\n    on appointments_appointment.uuid = seat.appointment_id\n  where is_registration_completed = 'true'\n  group by appointments_appointment.uuid\n) as apt\n  on  slot.uuid = apt.time_slot_id\nwhere DATE(slot.start) = CURRENT_DATE + interval '2 day'\nand location_id in (select id from appointments_location where name = '$location')\ngroup by\n  slot.start,\n  slot.capacity,\n  slot.usage"
    }
   ]
  },
  {
   "title": "All future seats booked",
   "type": "stat",
   "description": "excluding today",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "select \n  sum(apt.seats) as seats_taken\nfrom appointments_timeslot as slot\ninner join (\n  select\n    appointments_appointment.uuid,\n    time_slot_id,\n    count(seat.uuid) as seats\n  from appointments_appointment\n  inner join appointments_seat as seat\n    on appointments_appointment.uuid = seat.appointment_id\n  where is_registration_completed = 'true'\n  group by appointments_appointment.uuid\n) as apt\n  on  slot.uuid = apt.time_slot_id\nwhere slot.start >= DATE(NOW() + interval '1 day')\nand location_id in (select id from appointments_location where name = '$location')"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Customers Today who still need to come",
   "type": "table",
   "description": "This table won't be impacted by time scale adjustments!!\nAlso, it only shows appointments in the future.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \n  ROW_NUMBER() OVER (order by slot.start) as n, \n  slot.start as time,\n  payment.product_type,\n  qr.code,\n  regexp_replace(seat.full_name,'\\S*$','') as name,\n  regexp_replace(seat.email,'^.{0,8}','***') as seat_email\nfrom appointments_qrcode as qr\ninner join appointments_seat as seat on seat.uuid = qr.seat_id\ninner join appointments_appointment as appt on appt.uuid = seat.appointment_id\ninner join appointments_timeslot as slot on slot.uuid = appt.time_slot_id\ninner join payments_payment as payment on qr.seat_id = payment.seat_id\nwhere \n  DATE(slot.start) = CURRENT_DATE\n  AND seat.uuid NOT IN (SELECT seat_id FROM samples_sample)\n  AND appt.location_id in (select id from appointments_location where name = '$location')\n  "
    }
   ]
  },
  {
   "title": "Bookings Summary",
   "type": "table",
   "description": "Seats Actually Taken == the time slot have been chosen and registration have also been completed",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select \n  slot.start as time,\n  slot.capacity,\n  slot.usage,\n  sum(apt.seats) as seats_taken\nfrom appointments_timeslot as slot\ninner join (\n  select\n    appointments_appointment.uuid,\n    time_slot_id,\n    count(seat.uuid) as seats\n  from appointments_appointment\n  inner join appointments_seat as seat\n    on appointments_appointment.uuid = seat.appointment_id\n  where is_registration_completed = 'true'\n  group by appointments_appointment.uuid\n) as apt\n  on  slot.uuid = apt.time_slot_id\nwhere slot.start >= DATE(NOW())\nAND location_id in (select id from appointments_location where name = '$location')\ngroup by\n  slot.start,\n  slot.capacity,\n  slot.usage\n"
    }
   ]
  },
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Appointments Confirmed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM appointments_appointment\nWHERE\n  is_registration_completed = 'true'\n"
    }
   ]
  },
  {
   "title": "All Samples taken",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom samples_sample  "
    }
   ]
  },
  {
   "title": "All QR Codes in the system",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "targets": [
    {
     "rawSql": "select \n  count(*)\nfrom appointments_qrcode  "
    }
   ]
  },
  {
   "title": "ALL Registration NOT Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM appointments_appointment\nWHERE\n  is_registration_completed = 'false'"
    }
   ]
  }
 ]
}