{
 "title": "Tech",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SES Emails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Deliveries",
     "metricName": "Delivery",
     "namespace": "AWS/SES",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Bounces",
     "metricName": "Bounce",
     "namespace": "AWS/SES",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Incoming Traffic PUBLIC NLB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "net/noe-ecs-public-nlb/f4f6f3d228a4d583"
     },
     "metricName": "ActiveFlowCount",
     "namespace": "AWS/NetworkELB",
     "region": "eu-central-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Periodic Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "RuleName": "*" },
     "metricName": "Invocations",
     "namespace": "AWS/Events",
     "period": "60",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    },
    {
     "metricName": "FailedInvocations",
     "namespace": "AWS/Events",
     "period": "60",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}