# Generated by Django 3.0.5 on 2020-04-08 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(default='', max_length=255)),
                ('bill_type', models.CharField(choices=[('RECEIPT', 'receipt'), ('VAT_INVOICE', 'VAT invoice')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Appointment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
