# Generated by Django 3.0.5 on 2020-04-08 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
