# Generated by Django 3.0.5 on 2020-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='vial',
            field=models.CharField(default='', help_text='The identifier of the vial (the number below the barcode).', max_length=50),
            preserve_default=False,
        ),
    ]
