# Generated by Django 3.0.5 on 2020-04-29 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampled_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The time when it is extraxted from a real person', null=True),
        ),
    ]
