# Generated by Django 3.0.5 on 2020-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20200429_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='vial',
            field=models.CharField(help_text='The identifier of the vial (the number below the barcode).', max_length=50, unique=True),
        ),
    ]
