pipeline {
  agent {
    label 'boto3 && fabric'
  }

  environment {
      AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
      AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
      AWS_CLOUDFRONT_DISTRIBUTION_IDS = credentials('AWS_CLOUDFRONT_DISTRIBUTION_IDS')
  }

  stages {
    stage('Build') {
      steps {
        dir("code/frontend") {
          sh "fab deployment.build"
        }
      }
    }

    stage('Test') {
      steps {
        sh """echo "testing placeholder" """
      }
    }

    stage('Deploy') {
      steps {
        dir("code/frontend") {
          sh "fab deployment.deploy"
        }
      }
    }
  }
}
