pipeline {
  agent {
    label 'boto3 && fabric'
  }

  environment {
      AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
      AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
  }
  parameters {
    choice(name: 'ENV', choices: ['staging','production'], description: 'Environment to deploy the app to')
  }

  stages {
    stage('Build') {
      steps {
        dir("code/frontend") {
          sh "fab deployment.build:${params.ENV}"
        }
      }
    }

    stage('Test') {
      steps {
        sh """echo "testing placeholder" """
      }
    }

    stage('Deploy') {
      steps {
        dir("code/frontend") {
          sh "fab deployment.deploy:${params.ENV}"
        }
      }
    }
  }
}
