# Generated by Django 3.0.5 on 2020-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="question",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
