# Generated by Django 3.0.5 on 2020-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='answer_datatype',
            field=models.CharField(choices=[('BOOLEAN', 'boolean'), ('INTEGER', 'integer'), ('STRING', 'string')], default='string', max_length=20),
        ),
    ]
