# Generated by Django 3.0.5 on 2020-04-08 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_type', models.CharField(choices=[('SIMPLEPAY', 'SimplePay'), ('ON_SITE', 'On-site')], max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='HUF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Seat')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='HUF', max_length=3)),
                ('external_reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('WAITING_FOR_AUTHORIZATION', 'waiting for authorization'), ('AUTHORIZED', 'authorized'), ('WAITING_FOR_COMPLETION', 'waiting for completion'), ('COMPLETED', 'completed'), ('WAITING_FOR_REFUND', 'waiting for refund'), ('REFUNDED', 'refunded'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Payment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
