# Generated by Django 3.0.5 on 2020-04-22 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePayTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='HUF', max_length=3)),
                ('external_reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('WAITING_FOR_AUTHORIZATION', 'waiting for authorization'), ('AUTHORIZED', 'authorized'), ('WAITING_FOR_COMPLETION', 'waiting for completion'), ('COMPLETED', 'completed'), ('WAITING_FOR_REFUND', 'waiting for refund'), ('REFUNDED', 'refunded'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled')], default='CREATED', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SimplePay transaction',
                'verbose_name_plural': 'SimplePay transactions',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_type', models.CharField(choices=[('SIMPLEPAY', 'SimplePay'), ('ON_SITE', 'On-site')], max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='HUF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When this field is empty, no payment for the person has been made (yet).', null=True)),
                ('proof_number', models.CharField(blank=True, help_text='Printed receipt/bill number, healthcare number (TAJ kártya szám) or anything which proves this payment has been made.', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Anything important to note about this payment.')),
                ('seat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Seat')),
                ('simplepay_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.SimplePayTransaction')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
