# Generated by Django 3.0.5 on 2020-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('WAITING_FOR_AUTHORIZATION', 'waiting for authorization'), ('AUTHORIZED', 'authorized'), ('WAITING_FOR_COMPLETION', 'waiting for completion'), ('COMPLETED', 'completed'), ('WAITING_FOR_REFUND', 'waiting for refund'), ('REFUNDED', 'refunded'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled')], default='CREATED', max_length=255),
        ),
    ]
