# Generated by Django 3.0.5 on 2020-04-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200415_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='SimplePayTransaction',
        ),
        migrations.AlterModelOptions(
            name='simplepaytransaction',
            options={'ordering': ('created_at',), 'verbose_name': 'SimplePay transaction', 'verbose_name_plural': 'SimplePay transactions'},
        ),
    ]
