# Generated by Django 3.0.5 on 2020-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200429_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='simplepaytransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
