# Generated by Django 3.0.5 on 2020-04-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200418_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='simplepay_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.SimplePayTransaction'),
        ),
    ]
