# Generated by Django 3.0.5 on 2020-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200512_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='simplepay_transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='simplepay_transactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='payments', to='payments.SimplePayTransaction'),
        ),
    ]
