# Generated by Django 3.0.5 on 2020-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200418_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When this field is empty, no payment for the person has been made (yet).', null=True),
        ),
    ]
