# Generated by Django 3.0.5 on 2020-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, help_text='Anything important to note about this payment.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_number',
            field=models.CharField(blank=True, help_text='Printed receipt/bill number, healthcare number (TAJ kártya szám) or anything which proves this payment has been made.', max_length=255),
        ),
    ]
