# Generated by Django 3.0.5 on 2020-04-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20200418_1805'),
        ('payments', '0007_auto_20200418_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='seat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Seat'),
        ),
    ]
