# Generated by Django 3.0.5 on 2020-04-08 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(help_text='Primary communication channel with the patient.', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Only used for online payments with Simple, invoice and billing for now.', max_length=254)),
                ('gtc', models.CharField(help_text='Accepted version of General Terms and Conditions. Applied to everyone whose Seat belong to this Appointment.', max_length=10)),
                ('privacy_policy', models.CharField(help_text='Accepted version of privacy policy. Applied to everyone whose Seat belong to this Appointment.', max_length=10)),
                ('start', models.DateTimeField(help_text='The appointment is valid from this time.')),
                ('end', models.DateTimeField(help_text='The appointment is valid until this time. This probably should be handled more lightly than the start time.')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('healthcare_number', models.CharField(max_length=30)),
                ('identity_card_number', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address_line1', models.CharField(help_text='Street address', max_length=200)),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, building, floor, suite, door, etc...', max_length=200)),
                ('has_doctor_referral', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When this field is empty, no payment for the person has been made (yet).', null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField()),
                ('code', models.CharField(max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.Location'),
        ),
    ]
