# Generated by Django 3.0.5 on 2020-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
