# Generated by Django 3.0.5 on 2020-04-22 16:22

import appointments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=appointments.models.generate_uuid, max_length=40, unique=True)),
                ('seat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Seat')),
            ],
        ),
    ]
