# Generated by Django 3.0.5 on 2020-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
