# Generated by Django 3.0.5 on 2020-04-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200408_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.Location'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to='appointments.Appointment'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='appointments.Appointment'),
        ),
    ]
