# Generated by Django 3.0.5 on 2020-04-16 12:58

import appointments.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200416_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=appointments.models._generate_email_code, max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='appointments.Appointment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
