# Generated by Django 3.0.5 on 2020-04-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='healthcare_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
