# Generated by Django 3.0.5 on 2020-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='licence_plate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='normalized_licence_plate',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
