# Generated by Django 3.0.5 on 2020-04-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20200416_1628'),
        ('appointments', '0006_auto_20200416_1944'),
    ]

    operations = [
    ]
