# Generated by Django 3.0.5 on 2020-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_merge_20200416_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='email',
            field=models.EmailField(default='info@tesztallomas.hu', help_text='Notification email for the test results.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
