# Generated by Django 3.0.5 on 2020-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20200417_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_registration_completed',
            field=models.BooleanField(default=False, help_text='Set before the user is redirected to the "Successful registration" page'),
        ),
    ]
