# Generated by Django 3.0.5 on 2020-04-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_is_registration_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='paid_at',
        ),
    ]
