# Generated by Django 3.0.5 on 2020-04-18 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_seat_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('capacity', models.IntegerField(default=0, help_text='Determines how many Seats can book for this period.')),
                ('usage', models.IntegerField(default=0, help_text='Number of Seats who booked for this period')),
                ('is_active', models.BooleanField(default=True, help_text='Time Slot is only availabe to be booked for if active')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Location')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
