# Generated by Django 3.0.5 on 2020-04-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Time Slot is only availabe to be booked for if active.'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='usage',
            field=models.IntegerField(default=0, help_text="Number of Seats who booked for this period. This should't be edited by humans :)"),
        ),
    ]
